name: pak_voyage
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # Firebase Database
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  # firebase Storage
  firebase_storage: ^12.1.3
  # Firebase Auth
  firebase_auth: ^5.1.3
  # uuid
  uuid: ^4.4.2
  # Cached Network
  http: ^1.2.2
  cached_network_image: ^3.4.0
  # StateManagement
  provider: ^6.1.2
  intl: ^0.19.0
  # Image picker
  image_picker: ^1.1.2
  # Card
  flutter_credit_card: ^4.0.1
  # Icon Launcher


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/islamabad/
    - assets/images/karachi/
    - assets/images/lahore/
    - assets/images/multan/
    - assets/images/quetta/
    - assets/images/quetta/restaurant/
    - assets/images/peshawar/restaurant/
    - assets/images/islamabad/restaurant/
    - assets/images/multan/restaurant/
    - assets/images/lahore/restaurant/
    - assets/images/karachi/restaurant/
    - assets/images/tours images/Chitral/
    - assets/images/tours images/hunza/
    - assets/images/tours images/KPK/
    - assets/images/tours images/Muree/
    - assets/images/transportation/
    - assets/images/tours images/Swat/
    - assets/images/tours images/Azad Kashmir/
    - assets/images/islamabad/emergency/
    - assets/images/karachi/emergency/
    - assets/images/lahore/emergency/
    - assets/images/multan/emergency/
    - assets/images/quetta/emergency/
    





  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/Comfortaa-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
