// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCszgFTiSCBqhsfoaUpEQvglxJJ7TFKHMs',
    appId: '1:558731118870:web:e510a6072e4ec382e86837',
    messagingSenderId: '558731118870',
    projectId: 'pakvoyage-d9686',
    authDomain: 'pakvoyage-d9686.firebaseapp.com',
    storageBucket: 'pakvoyage-d9686.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOe3nl9YSSXD6c9vy8Ib7ULsmQS3iu3vY',
    appId: '1:558731118870:android:edeedd7a4f22b8e3e86837',
    messagingSenderId: '558731118870',
    projectId: 'pakvoyage-d9686',
    storageBucket: 'pakvoyage-d9686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbgOHhgeeguCfwb9ZkbGPwCltsvpatSQ',
    appId: '1:558731118870:ios:edad5ba62ecbf60fe86837',
    messagingSenderId: '558731118870',
    projectId: 'pakvoyage-d9686',
    storageBucket: 'pakvoyage-d9686.appspot.com',
    iosBundleId: 'com.example.pakVoyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbgOHhgeeguCfwb9ZkbGPwCltsvpatSQ',
    appId: '1:558731118870:ios:edad5ba62ecbf60fe86837',
    messagingSenderId: '558731118870',
    projectId: 'pakvoyage-d9686',
    storageBucket: 'pakvoyage-d9686.appspot.com',
    iosBundleId: 'com.example.pakVoyage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCszgFTiSCBqhsfoaUpEQvglxJJ7TFKHMs',
    appId: '1:558731118870:web:a03f12aa12168df9e86837',
    messagingSenderId: '558731118870',
    projectId: 'pakvoyage-d9686',
    authDomain: 'pakvoyage-d9686.firebaseapp.com',
    storageBucket: 'pakvoyage-d9686.appspot.com',
  );
}
